name: Linting

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4.0.3
        with:
          cache: npm

      - name: Install dependencies
        run: |
          set -xe
          make install/npm

      - name: Lint
        run: |
          set -xe
          make lint/npm

  golang:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Lint
        run: |
          set -xe
          make lint/go

  check:
    if: always()
    name: Linting Successful
    runs-on: ubuntu-latest
    needs: [golang, prettier]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
