name: Run Tests

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  golang-build:
    name: Building golang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use golang
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: |
          set -xe
          go get .

      - name: Build
        run: |
          set -xe
          make build/go

  golang-test:
    name: Testing golang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use golang
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: |
          set -xe
          make install/go

      - name: Test
        run: |
          set -xe
          make test/go

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [golang-test, golang-build]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
