name: Run Tests

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build_and_test:
    name: "Testing rust ${{ matrix.toolchain }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update rustup
        run: |
          set -xe
          rustup update ${{ matrix.toolchain }}

      - name: Use toolchain
        run: |
          set -xe
          rustup default ${{ matrix.toolchain }}

      - name: Build project
        run: |
          set -xe
          cargo build --verbose

      - name: Test
        run: |
          set -xe
          cargo test --verbose

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
